### ISSUE TITLE
Toml connection for snowflake 

### ISSUE THREAD

**Issue by jtouley** [jtouley/snowflake-excel-streamlit#4]
Look into switching config.yaml to toml

**Comment by jtouley** [comment]
> Look into switching config.yaml to toml

I've reviewed our configuration setup and propose switching from config.yaml to a TOML-based configuration to align with current best practices for Snowflake connections. Here’s a plan to make the transition smooth:

### 1. Update Configuration Loader:
Modify the configuration manager in excel_to_bronze/config.py to read a TOML file instead of YAML. For Python 3.11+, we can use the built-in tomllib; for earlier versions, we might include the toml package.

### 2. Rename and Update Sample Files:

Rename config/config.yaml and config/config.yaml.example to config/config.toml and config/config.toml.example, respectively.

Update the sample file with TOML syntax:
```toml
[snowflake]
account = "your_account"
user = "your_username"
password = "your_password"
warehouse = "your_warehouse"
database = "your_database"
schema = "your_schema"
```

### 3. Adjust the Setup Script:
Update config/setup.sh so that it creates the new TOML configuration file if one doesn’t already exist. This will ensure a seamless experience during the initial setup.

### 4. Revise Documentation:
Update the README and any relevant documentation to reflect the switch to TOML for configuration. This helps prevent any confusion during onboarding or deployment.

### 5. Consider Backward Compatibility:
Optionally, during a transition period, we could support both YAML and TOML by detecting which configuration file exists. A deprecation warning for YAML could be issued if both are found. Since there are minimal forks, this shouldn't be an issue.
